# Generated by Django 4.2.7 on 2023-11-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attendence_log_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_id',
            field=models.IntegerField(default=1),
        ),
    ]
